envVarGroups:
  - name: shopflix-production
    envVars:
      - key: DB_PASSWORD
        value: AVNS_478R2aHaIkIXTIR0s__
      - key: APP_KEY
        value: base64:ZyglX2iNJYdilwyoyegzP/5mgXyXC8b7zqHK0hd7Fy4=

services:
  - type: web
    name: shopflix-backend
    env: docker
    plan: free
    dockerCommand: ./scripts/deploy.sh
    envVars:
      - fromGroup: shopflix-production
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql-283fc8d8-hastechofficial-bcc5.l.aivencloud.com
      - key: DB_PORT
        value: "26764"
      - key: DB_DATABASE
        value: defaultdb
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_SSLMODE
        value: require
      - key: MYSQL_ATTR_SSL_VERIFY_SERVER_CERT
        value: "false"
      - key: ASSET_URL
        value: https://shopflix-blue.vercel.app/
      - key: APP_URL
        value: https://shopflix-backend.onrender.com # Change this once you have your final Render URL
      - key: BAGISTO_INSTALLATION_TYPE
        value: cream
      - key: FORCE_FRESH_INSTALL
        value: "false"
      - key: BAGISTO_SEED_BASE_DATA
        value: false




