services:
  - type: web
    name: shopflix-backend
    env: docker
    plan: free # Change to pro if needed
    dockerCommand: ./scripts/deploy.sh
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: shopflix-db
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        value: shopflix
      - key: DB_USERNAME
        value: shopflix_user
      - key: DB_PASSWORD
        generateValue: true

  - type: pserv
    name: shopflix-db
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: Dockerfile.mysql # We will create this
    envVars:
      - key: MYSQL_DATABASE
        value: shopflix
      - key: MYSQL_USER
        value: shopflix_user
      - key: MYSQL_PASSWORD
        fromService:
          name: shopflix-backend
          type: web
          property: envVar:DB_PASSWORD
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true

